### PR TITLE
Create Datasources via `ConfigMaps` (requires Grafana 5.x)

### PR DESCRIPTION
**Pull request by gdmello**
* Upgrade support to Grafana 5.x
* Create datasources via `ConfigMaps`
* Added unit tests

### CODE REVIEW

**Comment by gdmello** [comment]
@tsloughter - My first attempt at golang - feel free to review/critique and I will address.

**Comment by gdmello** [comment]
@tsloughter - any chance you could review this?

**Comment by tsloughter** [comment]
Sorry, forgot about this.

I'm no Gopher either, so I can't say much about the Go :). Though I doubt you need to do a `log.Println(fmt.Printf`, should be a log function that can format, I'd think.

I'm going to merge this but haven't verified it works myself. I don't know when I'll have time to play with this operator again and want it to continue moving along, so it may be better to hand it over to you? Or if you want me to keep acting as a reviewer and person to bounce ideas off of that is fine with me.

**Comment by gdmello** [comment]
@tsloughter - Thank you for reviewing! I'll have to look into the print bit and might open a PR depending on what I find.

I have tested this out on my k8s cluster, against a central grafana server in another namespace, it worked out fine.

As for handing over the operator to me, it's your piece of work, so it should remain with you. I am happy to be a reviewer for this repo, to help you out when other PRs come in. What do you think?

**Comment by gdmello** [comment]
@tsloughter - I'd like to add some other features to this operator - I'm ready to take on this repo, or be able to approve/merge PRs so this operator can move forward. What do you think?

**Comment by tsloughter** [comment]
@gdmello happy to hand over the ownership of the repo. I saw I got an email from you as well, I can reply there to work out details.

**Pull request merged**
